version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: microservicio_clinico_postgres
    environment:
      POSTGRES_DB: veterinaria_clinico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - veterinaria_network

volumes:
  postgres_data:

networks:
  veterinaria_network:
    driver: bridge